### ISSUE TITLE
Fix webpage window title

### ISSUE THREAD

**Issue by hourssincetalebcalledsomeoneafraud** [hourssincetalebcalledsomeoneafraud/hourssincetalebcalledsomeoneafraud.github.io#2]
Not sure why this isn't already working with the title (and description, just to be sure!) in _config.yaml, maybe README.md is not allowed to have the URL in it as that's determining the website title?

**Comment by prpcodes** [comment]
Hey, I'd like to take on that issue

**Comment by hourssincetalebcalledsomeoneafraud** [comment]
Fixed by #4 thank you so much!!
